import { getAllTasks } from './db';
import { format } from 'date-fns';

export interface DailyReportData {
  date: string;
  completedPercentage: number;
  criticalCompletionPercentage: number;
  compliancePercentage: number;
  totalTasks: number;
  completedTasks: number;
  criticalTasks: number;
  criticalCompleted: number;
  complianceTasks: number;
  complianceCompleted: number;
  topMisses: string[];
}

export async function generateDailyReport(): Promise<DailyReportData> {
  const tasks = await getAllTasks();
  const today = format(new Date(), 'yyyy-MM-dd');

  const todayTasks = tasks.filter((t) => {
    if (!t.dueAt) return false;
    const dueDate = format(new Date(t.dueAt), 'yyyy-MM-dd');
    return dueDate === today;
  });

  const totalTasks = todayTasks.length;
  const completedTasks = todayTasks.filter((t) => t.status === 'done').length;
  const completedPercentage = totalTasks > 0 ? Math.round((completedTasks / totalTasks) * 100) : 0;

  const criticalTasks = todayTasks.filter((t) => t.priority === 'critical');
  const criticalCompleted = criticalTasks.filter((t) => t.status === 'done').length;
  const criticalCompletionPercentage =
    criticalTasks.length > 0 ? Math.round((criticalCompleted / criticalTasks.length) * 100) : 100;

  const complianceTasks = todayTasks.filter((t) => t.complianceType);
  const complianceCompleted = complianceTasks.filter((t) => t.status === 'done').length;
  const compliancePercentage =
    complianceTasks.length > 0 ? Math.round((complianceCompleted / complianceTasks.length) * 100) : 100;

  const topMisses = todayTasks
    .filter((t) => t.status !== 'done' && t.priority === 'critical')
    .map((t) => t.title)
    .slice(0, 5);

  return {
    date: today,
    completedPercentage,
    criticalCompletionPercentage,
    compliancePercentage,
    totalTasks,
    completedTasks,
    criticalTasks: criticalTasks.length,
    criticalCompleted,
    complianceTasks: complianceTasks.length,
    complianceCompleted,
    topMisses,
  };
}

export function formatDailyReportAsEmail(report: DailyReportData): string {
  const statusIcon = report.criticalCompletionPercentage >= 95 && report.compliancePercentage >= 95 ? '✅' : '⚠️';

  return `${statusIcon} Culi.Flow - Daily Operations Report
${format(new Date(report.date), 'EEEE, MMMM d, yyyy')}

PERFORMANCE METRICS
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
✔️  Task Completion: ${report.completedPercentage}% (${report.completedTasks}/${report.totalTasks})
⚠️  Critical Tasks: ${report.criticalCompletionPercentage}% (${report.criticalCompleted}/${report.criticalTasks})
🔵 Compliance: ${report.compliancePercentage}% (${report.complianceCompleted}/${report.complianceTasks})

${report.topMisses.length > 0 ? `
INCOMPLETE CRITICAL TASKS
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
${report.topMisses.map((miss, i) => `${i + 1}. ${miss}`).join('\n')}
` : ''}
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Login to Culi.Flow for full task-level details and audit trail.

Generated by Culi.Flow V1.1 Cockpit
`;
}

export function formatDailyReportAsHTML(report: DailyReportData): string {
  const statusColor = report.criticalCompletionPercentage >= 95 && report.compliancePercentage >= 95 ? '#10b981' : '#f59e0b';

  return `
<!DOCTYPE html>
<html>
<head>
  <style>
    body { font-family: system-ui, sans-serif; background: #09090b; color: #fff; padding: 20px; }
    .container { max-width: 600px; margin: 0 auto; background: #18181b; border-radius: 8px; padding: 30px; }
    .header { font-size: 24px; font-weight: bold; margin-bottom: 10px; color: ${statusColor}; }
    .date { color: #a1a1aa; margin-bottom: 30px; }
    .metric { margin: 15px 0; padding: 15px; background: #27272a; border-radius: 6px; }
    .metric-label { color: #a1a1aa; font-size: 12px; text-transform: uppercase; }
    .metric-value { font-size: 32px; font-weight: bold; margin: 5px 0; }
    .list { margin: 20px 0; }
    .list-item { padding: 10px; background: #27272a; margin: 8px 0; border-radius: 4px; }
    .footer { margin-top: 30px; padding-top: 20px; border-top: 1px solid #3f3f46; color: #71717a; font-size: 12px; }
  </style>
</head>
<body>
  <div class="container">
    <div class="header">${report.criticalCompletionPercentage >= 95 && report.compliancePercentage >= 95 ? '✅' : '⚠️'} Culi.Flow Daily Report</div>
    <div class="date">${format(new Date(report.date), 'EEEE, MMMM d, yyyy')}</div>

    <div class="metric">
      <div class="metric-label">Task Completion</div>
      <div class="metric-value">${report.completedPercentage}%</div>
      <div style="color: #a1a1aa;">${report.completedTasks} of ${report.totalTasks} tasks</div>
    </div>

    <div class="metric">
      <div class="metric-label">Critical Tasks</div>
      <div class="metric-value" style="color: ${report.criticalCompletionPercentage >= 95 ? '#10b981' : '#ef4444'};">${report.criticalCompletionPercentage}%</div>
      <div style="color: #a1a1aa;">${report.criticalCompleted} of ${report.criticalTasks} completed</div>
    </div>

    <div class="metric">
      <div class="metric-label">Compliance</div>
      <div class="metric-value" style="color: ${report.compliancePercentage >= 95 ? '#10b981' : '#ef4444'};">${report.compliancePercentage}%</div>
      <div style="color: #a1a1aa;">${report.complianceCompleted} of ${report.complianceTasks} tasks</div>
    </div>

    ${report.topMisses.length > 0 ? `
    <div style="margin-top: 30px;">
      <div style="font-weight: bold; margin-bottom: 10px;">Incomplete Critical Tasks</div>
      <div class="list">
        ${report.topMisses.map((miss) => `<div class="list-item">${miss}</div>`).join('')}
      </div>
    </div>
    ` : ''}

    <div class="footer">
      Generated by Culi.Flow V1.1 Cockpit<br>
      Login for full task-level details and audit trail
    </div>
  </div>
</body>
</html>
`;
}

export function copyDailyReportToClipboard(report: DailyReportData): void {
  const text = formatDailyReportAsEmail(report);
  navigator.clipboard.writeText(text);
}

export function downloadDailyReportAsHTML(report: DailyReportData): void {
  const html = formatDailyReportAsHTML(report);
  const blob = new Blob([html], { type: 'text/html' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `daily-report-${report.date}.html`;
  a.click();
  URL.revokeObjectURL(url);
}
