import type { Task } from '../types';
import { createTask } from './db';
import { addHours, addMinutes } from 'date-fns';

export async function seedSampleData(): Promise<void> {
  const now = new Date();

  const sampleTasks: Omit<Task, 'id' | 'createdAt' | 'updatedAt'>[] = [
    // Critical Service Tasks
    {
      title: 'Mise en place - Ribeye station',
      type: 'prep',
      concept: 'oak-terrace',
      station: 'hot-line',
      owner: 'Mike',
      priority: 'critical',
      durationMinutes: 30,
      dueAt: addHours(now, 1).toISOString(),
      status: 'backlog',
      complianceType: undefined,
      evidenceRequired: false,
      evidence: [],
    },
    {
      title: 'Prep chicken stock 2 gal',
      type: 'prep',
      concept: 'oak-terrace',
      station: 'garde',
      owner: 'Sarah',
      priority: 'high',
      durationMinutes: 45,
      dueAt: addHours(now, 2).toISOString(),
      status: 'in_progress',
      complianceType: undefined,
      evidenceRequired: false,
      evidence: [],
    },
    {
      title: 'Temp log - Walk-in cooler',
      type: 'compliance',
      concept: 'central-production',
      station: 'utility',
      owner: 'Alex',
      priority: 'critical',
      durationMinutes: 5,
      dueAt: addMinutes(now, 30).toISOString(),
      status: 'backlog',
      complianceType: 'temp_log',
      evidenceRequired: true,
      evidence: [],
    },
    {
      title: 'Test meal - Salmon Nicoise',
      type: 'compliance',
      concept: 'elements',
      station: 'garde',
      owner: 'Chris',
      priority: 'high',
      durationMinutes: 10,
      dueAt: addHours(now, 3).toISOString(),
      status: 'backlog',
      complianceType: 'test_meal',
      evidenceRequired: true,
      evidence: [],
    },
    {
      title: 'Bake sourdough loaves 12 ea',
      type: 'prep',
      concept: 'oak-terrace',
      station: 'bakery',
      owner: 'Jamie',
      priority: 'medium',
      durationMinutes: 60,
      dueAt: addHours(now, 4).toISOString(),
      status: 'backlog',
      complianceType: undefined,
      evidenceRequired: false,
      evidence: [],
    },
    {
      title: 'Prep mirepoix for stock',
      type: 'prep',
      concept: 'central-production',
      station: 'central-production',
      owner: 'Taylor',
      priority: 'medium',
      durationMinutes: 20,
      dueAt: addHours(now, 1.5).toISOString(),
      status: 'ready',
      complianceType: undefined,
      evidenceRequired: false,
      evidence: [],
    },
    {
      title: 'FIFO rotation - Dairy cooler',
      type: 'compliance',
      concept: 'central-production',
      station: 'utility',
      owner: 'Jordan',
      priority: 'high',
      durationMinutes: 15,
      dueAt: addHours(now, 2).toISOString(),
      status: 'backlog',
      complianceType: 'fifo',
      evidenceRequired: true,
      evidence: [],
    },
    {
      title: 'Prep sauce bases for dinner service',
      type: 'prep',
      concept: 'elements',
      station: 'hot-line',
      owner: 'Morgan',
      priority: 'critical',
      durationMinutes: 40,
      dueAt: addMinutes(now, 45).toISOString(),
      status: 'in_progress',
      complianceType: undefined,
      evidenceRequired: false,
      evidence: [],
    },
    {
      title: 'Meal round - Resident feedback',
      type: 'compliance',
      concept: 'loons-nest',
      station: undefined,
      owner: 'Casey',
      priority: 'medium',
      durationMinutes: 20,
      dueAt: addHours(now, 5).toISOString(),
      status: 'backlog',
      complianceType: 'meal_round',
      evidenceRequired: true,
      evidence: [],
    },
    {
      title: 'Breakdown and sanitize dish station',
      type: 'admin',
      concept: undefined,
      station: 'dish',
      owner: 'Riley',
      priority: 'medium',
      durationMinutes: 30,
      dueAt: addHours(now, 8).toISOString(),
      status: 'backlog',
      complianceType: undefined,
      evidenceRequired: false,
      evidence: [],
    },
    {
      title: 'Plating photo - Ribeye special',
      type: 'standards',
      concept: 'oak-terrace',
      station: 'hot-line',
      owner: 'Sam',
      priority: 'high',
      durationMinutes: 10,
      dueAt: addHours(now, 3).toISOString(),
      status: 'backlog',
      complianceType: undefined,
      evidenceRequired: true,
      evidence: [],
    },
    {
      title: 'Prep garnish station for service',
      type: 'prep',
      concept: 'elements',
      station: 'garde',
      owner: 'Drew',
      priority: 'high',
      durationMinutes: 25,
      dueAt: addHours(now, 1).toISOString(),
      status: 'verified',
      complianceType: undefined,
      evidenceRequired: false,
      evidence: [],
    },
    // Some completed tasks for analytics
    {
      title: 'Morning temp logs completed',
      type: 'compliance',
      concept: 'central-production',
      station: 'utility',
      owner: 'Alex',
      priority: 'critical',
      durationMinutes: 10,
      dueAt: addHours(now, -2).toISOString(),
      status: 'done',
      complianceType: 'temp_log',
      evidenceRequired: true,
      evidence: ['temp-log-001.jpg'],
    },
    {
      title: 'Breakfast service prep completed',
      type: 'service',
      concept: 'oak-terrace',
      station: 'hot-line',
      owner: 'Mike',
      priority: 'critical',
      durationMinutes: 45,
      dueAt: addHours(now, -3).toISOString(),
      status: 'done',
      complianceType: undefined,
      evidenceRequired: false,
      evidence: [],
    },
  ];

  console.log('Seeding sample data...');

  for (const taskData of sampleTasks) {
    const task: Task = {
      ...taskData,
      id: `task-${Date.now()}-${Math.random().toString(36).substr(2, 9)}`,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    };

    await createTask(task);
  }

  console.log(`Seeded ${sampleTasks.length} sample tasks`);
}
